export const formFieldNames = {
  email: 'email',
  nickname: 'nickname',
  password: 'password',
  cover: 'cover',
  title: 'title',
  bpm: 'bpm',
  tags: 'tags',
  standardPrice: 'standardPrice',
  premiumPrice: 'premiumPrice',
  preview: 'preview',
  fullVersion: 'fullVersion',
  exclusiveVersion: 'exclusiveVersion',
  key: 'key',
} as const;
